import type { PhoneModel } from "@/types/catalog";

export const honorModels: PhoneModel[] = [
    { name: "HONOR Magic 8 Pro", year: 2026, image: "/honor/HONOR Magic 8 Pro.png" },
    { name: "HONOR Magic 8 Ultimate", year: 2026, image: "/honor/HONOR Magic 8 Ultimate.png" },
    { name: "HONOR Magic V4 (Fold)", year: 2026, image: "/honor/HONOR Magic V4 (Fold).png" },
    { name: "HONOR 120 Pro", year: 2026, image: "/honor/HONOR 120 Pro.png" },
    { name: "HONOR X11b", year: 2026, image: "/honor/HONOR X11b.png" },
    { name: "HONOR Magic 7 Pro", year: 2025, image: "/honor/HONOR Magic 7 Pro.png" },
    { name: "HONOR 110 Pro", year: 2025, image: "/honor/HONOR 110 Pro.png" },
    { name: "HONOR Magic V3", year: 2025, image: "/honor/HONOR Magic V3.png" },
    { name: "HONOR X10 Max 5G", year: 2025, image: "/honor/HONOR X10 Max 5G.png" },
    { name: "HONOR 200 Smart", year: 2025, image: "/honor/HONOR 200 Smart.png" },
    { name: "HONOR Magic 6 Pro", year: 2024, image: "/honor/HONOR Magic 6 Pro.png" },
    { name: "HONOR 200 Pro", year: 2024, image: "/honor/HONOR 200 Pro.png" },
    { name: "HONOR 200 Lite", year: 2024, image: "/honor/HONOR 200 Lite.png" },
    { name: "HONOR Magic V2", year: 2024, image: "/honor/HONOR Magic V2.png" },
    { name: "HONOR X9c 5G", year: 2024, image: "/honor/HONOR X9c 5G.png" },
    { name: "HONOR Magic 5 Pro", year: 2023, image: "/honor/HONOR Magic 5 Pro.png" },
    { name: "HONOR 90", year: 2023, image: "/honor/HONOR 90.png" },
    { name: "HONOR 70 5G", year: 2022, image: "/honor/HONOR 70 5G.png" },
    { name: "HONOR X8b", year: 2023, image: "/honor/honor-x8b-cyan.png" },
    { name: "HONOR X7a", year: 2023, image: "/honor/honor-x7a-sliver-list.png" },
    { name: "HONOR Magic 4 Pro", year: 2022, image: "/honor/HONOR Magic 4 Pro.png" },
    { name: "HONOR 50", year: 2021, image: "/honor/HONOR 50.png" },
    { name: "HONOR Magic 3 Pro", year: 2021, image: "/honor/HONOR Magic 3 Pro.png" },
    { name: "HONOR 30 Pro+", year: 2020, image: "/honor/HONOR 30 Pro+.png" },
    { name: "HONOR View 20", year: 2019, image: "/honor/HONOR View 20.png" },
    { name: "HONOR 20 Pro", year: 2019, image: "/honor/HONOR 20 Pro.png" },
    { name: "HONOR 10", year: 2018, image: "/honor/HONOR 10.png" },
    { name: "HONOR 8X", year: 2018, image: "/honor/HONOR 8X.png" },
    { name: "HONOR 9", year: 2017, image: "/honor/HONOR 9.png" },
    { name: "HONOR 8", year: 2016, image: "/honor/HONOR 8.png" },
];
