import type { PhoneModel } from "@/types/catalog";

export const huaweiModels: PhoneModel[] = [
    { name: "Huawei Pura 70", year: 2024, image: "/huawei/huawei-pura70.png" },
    { name: "Huawei P60 Pro", year: 2023, image: "/huawei/Huawei P60 Pro.png" },
    { name: "Huawei P50 Pro", year: 2021, image: "/huawei/Huawei P50 Pro.png" },
    { name: "Mate 60 Pro", year: 2023, image: "/huawei/Mate 60 Pro.png" },
    { name: "Huawei P30 Pro", year: 2019, image: "/huawei/Huawei P30 Pro.png" },
    { name: "Mate 20 Pro", year: 2018, image: "/huawei/Mate 20 Pro.png" },
    { name: "Huawei Mate 80 Pro", year: 2026, image: "/huawei/Huawei Mate 80 Pro.png" },
    { name: "Huawei Pura 80 Ultra", year: 2026, image: "/huawei/Huawei Pura 80 Ultra.png" },
    { name: "Huawei Mate XT Ultimate", year: 2025, image: "/huawei/Huawei Mate XT Ultimate.png" },
    { name: "Huawei Mate 70 Pro", year: 2025, image: "/huawei/Huawei Mate 70 Pro.jpg" },
    { name: "Huawei nova 13 Pro", year: 2025, image: "/huawei/Huawei nova 13 Pro.png" },
    { name: "Huawei Mate X6", year: 2024, image: "/huawei/Huawei Mate X6.png" },
    { name: "Huawei nova 12s", year: 2024, image: "/huawei/Huawei nova 12s.png" },
    { name: "Huawei Mate 50 Pro", year: 2022, image: "/huawei/Huawei Mate 50 Pro.png" },
    { name: "Huawei nova 10 Pro", year: 2022, image: "/huawei/Huawei nova 10 Pro.png" },
    { name: "Huawei Mate 40 Pro", year: 2020, image: "/huawei/Huawei Mate 40 Pro.png" },
    { name: "Huawei P40 Pro", year: 2020, image: "/huawei/Huawei P40 Pro.png" },
    { name: "Huawei Mate 30 Pro", year: 2019, image: "/huawei/Huawei Mate 30 Pro.png" },
    { name: "Huawei P20 Pro", year: 2018, image: "/huawei/Huawei P20 Pro.png" },
    { name: "Huawei Mate 10 Pro", year: 2017, image: "/huawei/Huawei Mate 10 Pro.png" },
    { name: "Huawei P10", year: 2017, image: "/huawei/Huawei P10.png" },
    { name: "Huawei P9", year: 2016, image: "/huawei/Huawei P9.png" },
    { name: "Huawei Mate 8", year: 2015, image: "/huawei/Huawei Mate 8.png" },
    { name: "Huawei Ascend P7", year: 2014, image: "/huawei/Huawei Ascend P7.png" },
    { name: "Huawei Ascend P6", year: 2013, image: "/huawei/Huawei Ascend P6.png" },
];
