import type { PhoneModel } from "@/types/catalog";

export const infinixModels: PhoneModel[] = [
    { name: "Note 40 Pro+", year: 2024, image: "/infinix/Note 40 Pro+.png" },
    { name: "Note 30 Pro", year: 2023, image: "/infinix/Note 30 Pro.png" },
    { name: "Zero 30 5G", year: 2023, image: "/infinix/Zero 30 5G.png" },
    { name: "Infinix Zero 60 Ultra", year: 2026, image: "/infinix/Infinix Zero 60 Ultra.png" },
    { name: "Infinix Note 60 Pro", year: 2026, image: "/infinix/Infinix Note 60 Pro.png" },
    { name: "Infinix GT 30 Pro", year: 2026, image: "/infinix/Infinix GT 30 Pro.png" },
    { name: "Infinix Hot 60 Pro", year: 2026, image: "/infinix/Infinix Hot 60 Pro.png" },
    { name: "Infinix Zero 50 Pro", year: 2025, image: "/infinix/Infinix Zero 50 Pro.png" },
    { name: "Infinix Note 50 Pro", year: 2025, image: "/infinix/Infinix Note 50 Pro.png" },
    { name: "Infinix GT 20 Pro", year: 2025, image: "/infinix/Infinix GT 20 Pro.png" },
    { name: "Infinix Hot 50 5G", year: 2025, image: "/infinix/Infinix Hot 50 5G.png" },
    { name: "Infinix Smart 9", year: 2025, image: "/infinix/Infinix Smart 9.png" },
    { name: "Infinix Zero 40 5G", year: 2024, image: "/infinix/Infinix Zero 40 5G.png" },
    { name: "Infinix Note 40 Pro", year: 2024, image: "/infinix/Infinix Note 40 Pro.png" },
    { name: "Infinix Hot 40 Pro", year: 2024, image: "/infinix/Infinix Hot 40 Pro.png" },
    { name: "Infinix GT 10 Pro", year: 2024, image: "/infinix/Infinix GT 10 Pro.png" },
    { name: "Infinix Smart 8 Pro", year: 2024, image: "/infinix/Infinix Smart 8 Pro.png" },
    { name: "Infinix Note 30 VIP", year: 2023, image: "/infinix/Infinix Note 30 VIP.png" },
    { name: "Infinix Hot 30i", year: 2023, image: "/infinix/Infinix Hot 30i.png" },
    { name: "Infinix Smart 7", year: 2023, image: "/infinix/Infinix Smart 7.png" },
    { name: "Infinix Zero Ultra", year: 2022, image: "/infinix/Infinix Zero Ultra.png" },
    { name: "Infinix Note 12 Pro 5G", year: 2022, image: "/infinix/Infinix Note 12 Pro 5G.png" },
    { name: "Infinix Hot 20 5G", year: 2022, image: "/infinix/Infinix Hot 20 5G.png" },
    { name: "Infinix Zero 20", year: 2022, image: "/infinix/Infinix Zero 20.png" },
    { name: "Infinix Zero X Pro", year: 2021, image: "/infinix/Infinix Zero X Pro.png" },
    { name: "Infinix Note 11 Pro", year: 2021, image: "/infinix/Infinix Note 11 Pro.png" },
    { name: "Infinix Note 10 Pro", year: 2021, image: "/infinix/Infinix Note 10 Pro.png" },
    { name: "Infinix Zero 8", year: 2020, image: "/infinix/Infinix Zero 8.png" },
    { name: "Infinix Note 7", year: 2020, image: "/infinix/Infinix Note 7.png" },
    { name: "Infinix S5 Pro", year: 2020, image: "/infinix/Infinix S5 Pro.png" },
    { name: "Infinix Hot 8", year: 2019, image: "/infinix/Infinix Hot 8.png" },
    { name: "Infinix Zero 6", year: 2019, image: "/infinix/Infinix Zero 6.png" },
    { name: "Infinix Note 5", year: 2018, image: "/infinix/Infinix Note 5.png" },
];
