import type { PhoneModel } from "@/types/catalog";

export const motorolaModels: PhoneModel[] = [
    { name: "Motorola Edge 70 Ultra", year: 2026, image: "/motorola/Motorola Edge 70 Ultra.png" },
    { name: "Motorola Razr 60 Ultra", year: 2026, image: "/motorola/Motorola Razr 60 Ultra.png" },
    { name: "Motorola Moto G95", year: 2026, image: "/motorola/Motorola Moto G95.png" },
    { name: "Motorola Edge 60 Pro", year: 2025, image: "/motorola/Motorola Edge 60 Pro.png" },
    { name: "Motorola Razr 50 Ultra", year: 2025, image: "/motorola/Motorola Razr 50 Ultra.png" },
    { name: "Motorola Moto G85", year: 2025, image: "/motorola/Motorola Moto G85.png" },
    { name: "Motorola Edge 50 Ultra", year: 2024, image: "/motorola/Motorola Edge 50 Ultra.png" },
    { name: "Motorola Edge 50 Pro", year: 2024, image: "/motorola/Motorola Edge 50 Pro.png" },
    { name: "Motorola Edge 50 Fusion", year: 2024, image: "/motorola/Motorola Edge 50 Fusion.png" },
    { name: "Motorola Moto G24", year: 2024, image: "/motorola/Motorola Moto G24.png" },
    { name: "Motorola Moto G04", year: 2024, image: "/motorola/Motorola Moto G04.png" },
    { name: "Motorola Razr 40 Ultra", year: 2023, image: "/motorola/Motorola Razr 40 Ultra.png" },
    { name: "Motorola Edge 40 Pro", year: 2023, image: "/motorola/Motorola Edge 40 Pro.png" },
    { name: "Motorola Edge 40 Neo", year: 2023, image: "/motorola/Motorola Edge 40 Neo.png" },
    { name: "Motorola Moto G84", year: 2023, image: "/motorola/Motorola Moto G84.png" },
    { name: "Motorola Moto G54", year: 2023, image: "/motorola/Motorola Moto G54.png" },
    { name: "Motorola Moto G14", year: 2023, image: "/motorola/Motorola Moto G14.png" },
    { name: "Motorola Edge 30 Ultra", year: 2022, image: "/motorola/Motorola Edge 30 Ultra.png" },
    { name: "Motorola Edge 30 Fusion", year: 2022, image: "/motorola/Motorola Edge 30 Fusion.png" },
    { name: "Motorola Moto G72", year: 2022, image: "/motorola/Motorola Moto G72.png" },
    { name: "Motorola Moto G42", year: 2022, image: "/motorola/Motorola Moto G42.png" },
    { name: "Motorola Moto G200 5G", year: 2021, image: "/motorola/Motorola Moto G200 5G.png" },
    { name: "Motorola Moto G100", year: 2021, image: "/motorola/Motorola Moto G100.png" },
    { name: "Motorola Moto G60", year: 2021, image: "/motorola/Motorola Moto G60.png" },
    { name: "Motorola Edge 20 Pro", year: 2021, image: "/motorola/Motorola Edge 20 Pro.png" },
];
