import type { PhoneModel } from "@/types/catalog";

export const oneplusModels: PhoneModel[] = [
    { name: "OnePlus 14", year: 2026, image: "/oneplus/OnePlus 14.png" },
    { name: "OnePlus Open 2", year: 2026, image: "/oneplus/OnePlus Open 2.png" },
    { name: "OnePlus 13", year: 2025, image: "/oneplus/OnePlus 13.png" },
    { name: "OnePlus 13R", year: 2025, image: "/oneplus/OnePlus 13R.png" },
    { name: "OnePlus Nord 5", year: 2025, image: "/oneplus/OnePlus Nord 5.png" },
    { name: "OnePlus 12", year: 2024, image: "/oneplus/OnePlus 12.png" },
    { name: "OnePlus 12R", year: 2024, image: "/oneplus/OnePlus 12R.png" },
    { name: "OnePlus Open", year: 2024, image: "/oneplus/OnePlus Open.png" },
    { name: "OnePlus Nord 4", year: 2024, image: "/oneplus/OnePlus Nord 4.png" },
    { name: "OnePlus Ace 3", year: 2024, image: "/oneplus/OnePlus Ace 3.png" },
    { name: "OnePlus 11", year: 2023, image: "/oneplus/OnePlus 11.png" },
    { name: "OnePlus 11R", year: 2023, image: "/oneplus/OnePlus 11R.png" },
    { name: "OnePlus Nord 3", year: 2023, image: "/oneplus/OnePlus Nord 3.png" },
    { name: "OnePlus Nord N30 5G", year: 2023, image: "/oneplus/OnePlus Nord N30 5G.png" },
    { name: "OnePlus 10 Pro", year: 2022, image: "/oneplus/OnePlus 10 Pro.png" },
    { name: "OnePlus 10T", year: 2022, image: "/oneplus/OnePlus 10.png" },
    { name: "OnePlus Nord 2T", year: 2022, image: "/oneplus/OnePlus Nord 2T.png" },
    { name: "OnePlus Nord N20 5G", year: 2022, image: "/oneplus/OnePlus Nord N20 5G.png" },
    { name: "OnePlus 9 Pro", year: 2021, image: "/oneplus/OnePlus 9 Pro.png" },
    { name: "OnePlus 9", year: 2021, image: "/oneplus/OnePlus 9.png" },
    { name: "OnePlus Nord 2", year: 2021, image: "/oneplus/OnePlus Nord 2.png" },
    { name: "OnePlus Nord N200 5G", year: 2021, image: "/oneplus/OnePlus Nord N200 5G.png" },
    { name: "OnePlus 8 Pro", year: 2020, image: "/oneplus/OnePlus 8 Pro.png" },
    { name: "OnePlus 8T", year: 2020, image: "/oneplus/OnePlus 8T.png" },
    { name: "OnePlus 8", year: 2020, image: "/oneplus/OnePlus 8.png" },
    { name: "OnePlus Nord", year: 2020, image: "/oneplus/OnePlus Nord.png" },
    { name: "OnePlus Nord N10 5G", year: 2020, image: "/oneplus/OnePlus Nord N10 5G.png" },
    { name: "OnePlus 7 Pro", year: 2019, image: "/oneplus/OnePlus 7 Pro.png" },
    { name: "OnePlus 7T", year: 2019, image: "/oneplus/OnePlus 7T.png" },
    { name: "OnePlus 6T", year: 2018, image: "/oneplus/OnePlus 6T.png" },
];
