import type { PhoneModel } from "@/types/catalog";

export const oppoModels: PhoneModel[] = [
    { name: "OPPO Find X7 Ultra", year: 2024, image: "/oppo/OPPO Find X7 Ultra.png" },
    { name: "OPPO Find X6 Pro", year: 2023, image: "/oppo/OPPO Find X6 Pro.png" },
    { name: "OPPO Reno 12 Pro", year: 2024, image: "/oppo/OPPO Reno 12 Pro.png" },
    { name: "OPPO Reno 11 Pro", year: 2023, image: "/oppo/OPPO Reno 11 Pro.png" },
    { name: "OPPO A98", year: 2023, image: "/oppo/OPPO A98.png" },
    { name: "OPPO A78", year: 2023, image: "/oppo/OPPO A78.png" },
    { name: "OPPO Find X9 Ultra", year: 2026, image: "/oppo/OPPO Find X9 Ultra.png" },
    { name: "OPPO Reno 14 Pro+", year: 2026, image: "/oppo/OPPO Reno 14 Pro+.png" },
    { name: "OPPO Find N5 (Fold)", year: 2026, image: "/oppo/OPPO Find N5 (Fold).png" },
    { name: "OPPO A100 Pro", year: 2026, image: "/oppo/OPPO A100 Pro.png" },
    { name: "OPPO K13 Pro", year: 2026, image: "/oppo/OPPO K13 Pro.png" },
    { name: "OPPO Find X8 Ultra", year: 2025, image: "/oppo/OPPO Find X8 Ultra.png" },
    { name: "OPPO Reno 13 Pro", year: 2025, image: "/oppo/OPPO Reno 13 Pro.png" },
    { name: "OPPO Find N4 Flip", year: 2025, image: "/oppo/OPPO Find N4 Flip.png" },
    { name: "OPPO A99", year: 2025, image: "/oppo/OPPO A99.png" },
    { name: "OPPO F27 Pro+", year: 2025, image: "/oppo/OPPO F27 Pro+.png" },
    { name: "OPPO Find N3 (Fold)", year: 2024, image: "/oppo/OPPO Find N3 (Fold).png" },
    { name: "OPPO Reno 12", year: 2024, image: "/oppo/OPPO Reno 12.png" },
    { name: "OPPO A60", year: 2024, image: "/oppo/OPPO A60.png" },
    { name: "OPPO K12", year: 2024, image: "/oppo/OPPO K12.png" },
    { name: "OPPO Find X5 Pro", year: 2022, image: "/oppo/OPPO Find X5 Pro.png" },
    { name: "OPPO Reno 10 Pro+", year: 2023, image: "/oppo/OPPO Reno 10 Pro+.png" },
    { name: "OPPO Reno 8 Pro", year: 2022, image: "/oppo/OPPO Reno 8 Pro.png" },
    { name: "OPPO Find N2 Flip", year: 2022, image: "/oppo/OPPO Find N2 Flip.png" },
    { name: "OPPO A58", year: 2023, image: "/oppo/OPPO A58.png" },
    { name: "OPPO Find X3 Pro", year: 2021, image: "/oppo/OPPO Find X3 Pro.png" },
    { name: "OPPO Reno 6 Pro", year: 2021, image: "/oppo/OPPO Reno 6 Pro.png" },
    { name: "OPPO Find X2 Pro", year: 2020, image: "/oppo/OPPO Find X2 Pro.png" },
    { name: "OPPO Reno 4 Pro", year: 2020, image: "/oppo/OPPO Reno 4 Pro.png" },
    { name: "OPPO Find X", year: 2018, image: "/oppo/OPPO Find X.png" },
    { name: "OPPO R11", year: 2017, image: "/oppo/OPPO R11.png" },
    { name: "OPPO N1", year: 2013, image: "/oppo/OPPO N1.png" },
];
