import type { PhoneModel } from "@/types/catalog";

export const realmeModels: PhoneModel[] = [
    { name: "Realme GT 6", year: 2024, image: "/realme/Realme GT 6.png" },
    { name: "Realme GT Neo 6", year: 2024, image: "/realme/Realme GT Neo 6.png" },
    { name: "Realme 12 Pro+", year: 2024, image: "/realme/Realme 12 Pro+.png" },
    { name: "Realme 11 Pro", year: 2023, image: "/realme/Realme 11 Pro.png" },
    { name: "Realme C67", year: 2024, image: "/realme/Realme C67.png" },
    { name: "Realme C53", year: 2023, image: "/realme/Realme C53.png" },
    { name: "Realme GT 8 Ultra", year: 2026, image: "/realme/Realme GT 8 Ultra.png" },
    { name: "Realme 15 Pro Max", year: 2026, image: "/realme/Realme 15 Pro Max.png" },
    { name: "Realme GT Neo 8", year: 2026, image: "/realme/Realme GT Neo 8.png" },
    { name: "Realme C85", year: 2026, image: "/realme/Realme C85.png" },
    { name: "Realme Narzo 80 Pro", year: 2026, image: "/realme/Realme Narzo 80 Pro.png" },
    { name: "Realme GT 7 Pro", year: 2025, image: "/realme/Realme GT 7 Pro.png" },
    { name: "Realme 14 Pro+", year: 2025, image: "/realme/Realme 14 Pro+.png" },
    { name: "Realme GT Neo 7", year: 2025, image: "/realme/Realme GT Neo 7.png" },
    { name: "Realme C75", year: 2025, image: "/realme/Realme C75.png" },
    { name: "Realme GT 5", year: 2023, image: "/realme/Realme GT 5.png" },
    { name: "Realme 11 Pro+", year: 2023, image: "/realme/Realme 11 Pro+.png" },
    { name: "Realme GT 2 Pro", year: 2022, image: "/realme/Realme GT 2 Pro.png" },
    { name: "Realme 10 Pro+", year: 2022, image: "/realme/Realme 10 Pro+.png" },
    { name: "Realme C55", year: 2023, image: "/realme/Realme C55.png" },
    { name: "Realme GT Master Edition", year: 2021, image: "/realme/Realme GT Master Edition.png" },
    { name: "Realme 9 Pro+", year: 2022, image: "/realme/Realme 9 Pro+.png" },
    { name: "Realme 8 Pro", year: 2021, image: "/realme/Realme 8 Pro.png" },
    { name: "Realme 7 Pro", year: 2020, image: "/realme/Realme 7 Pro.png" },
    { name: "Realme X50 Pro 5G", year: 2020, image: "/realme/Realme X50 Pro 5G.png" },
    { name: "Realme X2 Pro", year: 2019, image: "/realme/Realme X2 Pro.png" },
    { name: "Realme 1", year: 2018, image: "/realme/Realme 1.png" },
];
