import type { PhoneModel } from "@/types/catalog";

export const samsungModels: PhoneModel[] = [
    { name: "Galaxy S25 Ultra", year: 2025, image: "/samsung/Galaxy_S25_Black.png" },
    { name: "Galaxy S24 Ultra", year: 2024, image: "/samsung/S24_Blueblack.png" },
    { name: "Galaxy S24+", year: 2024, image: "/samsung/S24+.png" },
    { name: "Galaxy A55", year: 2024, image: "/samsung/SamsungGalaxyA535G.png" },
    { name: "Galaxy S23 Ultra", year: 2023, image: "/samsung/Samsung_Galaxy_S23_Ultra,_512_GB,_Lavender_20230416_HOF00318_RAW-Export_cens.png" },
    { name: "Galaxy S23", year: 2023, image: "/samsung/Galaxy_S23_(cropped).png" },
    { name: "Galaxy A54", year: 2023, image: "/samsung/A54.png" },
    { name: "Galaxy Z Fold5", year: 2023, image: "/samsung/Z Fold5.png" },
    { name: "Galaxy Z Flip5", year: 2023, image: "/samsung/Z Flip5.png" },
    { name: "Galaxy S22 Ultra", year: 2022, image: "/samsung/galaxy-s22-ultra.png" },
    { name: "Galaxy A53", year: 2022, image: "/samsung/SamsungGalaxyA535G.png" },
    { name: "Galaxy S21 Ultra", year: 2021, image: "/samsung/Galaxy_S21_Ultra_vector.png" },
    { name: "Galaxy S20", year: 2020, image: "/samsung/Samsung_Galaxy_S20_Ultra.png" },
    { name: "Galaxy S10", year: 2019, image: "/samsung/Samsung_Galaxy_S10+.png" },
    { name: "Galaxy S26 Ultra", year: 2026, image: "/samsung/samsung-galaxy-s26-ultra.png" },
    { name: "Galaxy S26", year: 2026, image: "/samsung/S26.png" },
    { name: "Galaxy Z Fold6", year: 2024, image: "/samsung/Z Fold6.png" },
    { name: "Galaxy S21 FE", year: 2022, image: "/samsung/GalaxyS21+.png" },
    { name: "Galaxy S9", year: 2018, image: "/samsung/Samsung_Galaxy_S9.png" },
    { name: "Galaxy S8", year: 2017, image: "/samsung/Samsung_Galaxy_S8_Patent.png" },
    { name: "Galaxy S7 Edge", year: 2016, image: "/samsung/Samsung_Galaxy_S7.png" },
    { name: "Galaxy S6", year: 2015, image: "/samsung/Samsung_Galaxy_S6.png" },
    { name: "Galaxy S5", year: 2014, image: "/samsung/Samsung_Galaxy_S5.png" },
    { name: "Galaxy S4", year: 2013, image: "/samsung/Samsung_Galaxy_S4.svg.png" },
    { name: "Galaxy S3", year: 2012, image: "/samsung/Samsung_Galaxy_S_III.png" },
    { name: "Galaxy S2", year: 2011, image: "/samsung/Samsung_Galaxy_SII.png" },
    { name: "Galaxy S", year: 2010, image: "/samsung/Samsung_Galaxy_S_White.png" },
];
