import type { PhoneModel } from "@/types/catalog";

export const tecnoModels: PhoneModel[] = [
    { name: "Tecno Spark 50 5G", year: 2026, image: "/tecno/Tecno Spark 50 5G.png" },
    { name: "Tecno Spark 50", year: 2026, image: "/tecno/Tecno Spark 50.png" },
    { name: "Tecno Spark 40 Pro+", year: 2026, image: "/tecno/Tecno Spark 40 Pro+.png" },
    { name: "Tecno Spark Slim", year: 2026, image: "/tecno/Tecno Spark Slim.png" },
    { name: "Tecno Spark Go 5G (2026)", year: 2026, image: "/tecno/Tecno Spark Go 5G (2026).png" },
    { name: "Tecno Spark 40", year: 2025, image: "/tecno/Tecno Spark 40.png" },
    { name: "Tecno Spark 30 Pro", year: 2025, image: "/tecno/Tecno Spark 30 Pro.png" },
    { name: "Tecno Spark 30 5G", year: 2025, image: "/tecno/Tecno Spark 30 5G.png" },
    { name: "Tecno Spark 30C", year: 2025, image: "/tecno/Tecno Spark 30C.png" },
    { name: "Tecno Spark 20 Pro 5G", year: 2024, image: "/tecno/Tecno Spark 20 Pro 5G.png" },
    { name: "Tecno Spark 20 Pro+", year: 2024, image: "/tecno/Tecno Spark 20 Pro+.png" },
    { name: "Tecno Spark 20P", year: 2024, image: "/tecno/Tecno Spark 20P.png" },
    { name: "Tecno Spark Go 2024", year: 2024, image: "/tecno/Tecno Spark Go 2024.png" },
    { name: "Tecno Spark 20 Pro", year: 2023, image: "/tecno/Tecno Spark 20 Pro.png" },
    { name: "Tecno Spark 20", year: 2023, image: "/tecno/Tecno Spark 20.png" },
    { name: "Tecno Spark 10 Pro", year: 2023, image: "/tecno/Tecno Spark 10 Pro.png" },
    { name: "Tecno Spark 10 5G", year: 2023, image: "/tecno/Tecno Spark 10 5G.png" },
    { name: "Tecno Spark Go 2023", year: 2023, image: "/tecno/Tecno Spark Go 2023.png" },
    { name: "Tecno Spark 9 Pro", year: 2022, image: "/tecno/Tecno Spark 9 Pro" },
    { name: "Tecno Spark 9T", year: 2022, image: "/tecno/Tecno Spark 9T.png" },
    { name: "Tecno Spark 8C", year: 2022, image: "/tecno/Tecno Spark 8C.jpg" },
    { name: "Tecno Spark 8P", year: 2021, image: "/tecno/Tecno Spark 8P.png" },
    { name: "Tecno Spark 8", year: 2021, image: "/tecno/Tecno Spark 8.png" },
    { name: "Tecno Spark 7 Pro", year: 2021, image: "/tecno/Tecno Spark 7 Pro.png" },
    { name: "Tecno Spark 7T", year: 2021, image: "/tecno/Tecno Spark 7T.png" },
    { name: "Tecno Spark 6", year: 2020, image: "/tecno/Tecno Spark 6.png" },
    { name: "Tecno Spark 5 Pro", year: 2020, image: "/tecno/Tecno Spark 5 Pro.png" },
    { name: "Tecno Spark 4", year: 2019, image: "/tecno/Tecno Spark 4.png" },
    { name: "Tecno Spark 3 Pro", year: 2019, image: "/tecno/Tecno Spark 3 Pro.png" },
    { name: "Tecno Spark 2", year: 2018, image: "/tecno/Tecno Spark 2.png" },
    { name: "Tecno Spark K7", year: 2017, image: "/tecno/Tecno Spark K7.png" },
];
