import type { PhoneModel } from "@/types/catalog";

export const xiaomiModels: PhoneModel[] = [
    { name: "Xiaomi 17 Ultra", year: 2026, image: "/xiaomi/Xiaomi 17 Ultra.png" },
    { name: "Xiaomi 17 Pro", year: 2026, image: "/xiaomi/Xiaomi 17 Pro.png" },
    { name: "POCO F8 Ultra", year: 2026, image: "/xiaomi/POCO F8 Ultra.png" },
    { name: "Redmi Note 15 Pro+", year: 2026, image: "/xiaomi/Redmi Note 15 Pro+.png" },
    { name: "POCO X8 Pro Max", year: 2026, image: "/xiaomi/POCO X8 Pro Max.png" },
    { name: "Xiaomi 15 Ultra", year: 2025, image: "/xiaomi/Xiaomi 15 Ultra.png" },
    { name: "Xiaomi 15T Pro", year: 2025, image: "/xiaomi/Xiaomi 15T Pro.png" },
    { name: "Redmi K90 Pro Max", year: 2025, image: "/xiaomi/Redmi K90 Pro Max.png" },
    { name: "POCO F7 Pro", year: 2025, image: "/xiaomi/POCO F7 Pro.png" },
    { name: "Xiaomi 14 Ultra", year: 2024, image: "/xiaomi/Xiaomi 14 Ultra.png" },
    { name: "Xiaomi Mix Flip", year: 2024, image: "/xiaomi/Xiaomi Mix Flip.png" },
    { name: "Redmi Note 14 Pro+", year: 2024, image: "/xiaomi/Redmi Note 14 Pro+.png" },
    { name: "POCO X6 Pro", year: 2024, image: "/xiaomi/POCO X6 Pro.png" },
    { name: "Xiaomi 13 Ultra", year: 2023, image: "/xiaomi/Xiaomi 13 Ultra.png" },
    { name: "Xiaomi 13T Pro", year: 2023, image: "/xiaomi/Xiaomi 13T Pro.png" },
    { name: "Redmi Note 13 Pro 5G", year: 2023, image: "/xiaomi/Redmi Note 13 Pro 5G.png" },
    { name: "POCO F5 Pro", year: 2023, image: "/xiaomi/POCO F5 Pro.png" },
    { name: "Xiaomi 12 Pro", year: 2022, image: "/xiaomi/Xiaomi 12 Pro.png" },
    { name: "Xiaomi 12S Ultra", year: 2022, image: "/xiaomi/Xiaomi 12S Ultra.png" },
    { name: "Redmi Note 12 Pro+", year: 2022, image: "/xiaomi/Redmi Note 12 Pro+.png" },
    { name: "POCO X4 Pro 5G", year: 2022, image: "/xiaomi/POCO X4 Pro 5G.png" },
    { name: "Xiaomi Mi 11 Ultra", year: 2021, image: "/xiaomi/Xiaomi Mi 11 Ultra.png" },
    { name: "Xiaomi 11T Pro", year: 2021, image: "/xiaomi/Xiaomi 11T Pro.png" },
    { name: "Redmi Note 10 Pro", year: 2021, image: "/xiaomi/Redmi Note 10 Pro.png" },
    { name: "POCO F3", year: 2021, image: "/xiaomi/POCO F3.png" },
    { name: "Xiaomi Mi 10 Pro", year: 2020, image: "/xiaomi/Xiaomi Mi 10 Pro.png" },
    { name: "POCO X3 NFC", year: 2020, image: "/xiaomi/POCO X3 NFC.png" },
    { name: "Xiaomi Mi 9", year: 2019, image: "/xiaomi/Xiaomi Mi 9.png" },
    { name: "Redmi Note 7", year: 2019, image: "/xiaomi/Redmi Note 7.png" },
    { name: "Xiaomi Mi A2", year: 2018, image: "/xiaomi/Xiaomi Mi A2.png" },
    { name: "POCO F1", year: 2018, image: "/xiaomi/POCO F1.png" },
];
