import type { PhoneModel } from "@/types/catalog";

export const zteModels: PhoneModel[] = [
    { name: "ZTE Axon 50 Ultra", year: 2023, image: "/zte/ZTE Axon 50 Ultra.png" },
    { name: "ZTE Axon 40 Pro", year: 2022, image: "/zte/ZTE Axon 40 Pro.png" },
    { name: "ZTE Blade V50", year: 2023, image: "/zte/ZTE Blade V50.png" },
    { name: "ZTE Nubia Z60 Ultra", year: 2024, image: "/zte/ZTE Nubia Z60 Ultra.png" },
    { name: "ZTE Nubia Red Magic 9 Pro", year: 2023, image: "/zte/ZTE Nubia Red Magic 9 Pro.png" },
    { name: "ZTE Nubia Z80 Ultra", year: 2026, image: "/zte/ZTE Nubia Z70 Ultra.png" },
    { name: "ZTE Red Magic 11 Pro", year: 2026, image: "/zte/ZTE Red Magic 11 Pro.png" },
    { name: "ZTE Axon 70 Ultra", year: 2026, image: "/zte/ZTE Axon 70 Ultra.png" },
    { name: "ZTE Blade V70 Design", year: 2026, image: "/zte/ZTE Blade V70 Design.png" },
    { name: "ZTE Libero Flip 2", year: 2026, image: "/zte/ZTE Libero Flip 2.png" },
    { name: "ZTE Nubia Z70 Ultra", year: 2025, image: "/zte/ZTE Nubia Z70 Ultra.png" },
    { name: "ZTE Red Magic 10 Pro", year: 2025, image: "/zte/ZTE Red Magic 10 Pro.png" },
    { name: "ZTE Axon 60 Ultra", year: 2024, image: "/zte/ZTE Axon 60 Ultra.png" },
    { name: "ZTE Blade V60 Vita", year: 2025, image: "/zte/ZTE Blade V60 Vita.png" },
    { name: "ZTE Nubia Flip 5G", year: 2024, image: "/zte/ZTE Nubia Flip 5G.png" },
    { name: "ZTE Nubia Z50S Pro", year: 2023, image: "/zte/ZTE Nubia Z50S Pro.png" },
    { name: "ZTE Red Magic 8S Pro", year: 2023, image: "/zte/ZTE Red Magic 8S Pro.png" },
    { name: "ZTE Blade V40 Design", year: 2022, image: "/zte/ZTE Blade V40 Design.png" },
    { name: "ZTE Axon 40 Ultra", year: 2022, image: "/zte/ZTE Axon 40 Ultra.png" },
    { name: "ZTE Axon 30 5G", year: 2021, image: "/zte/ZTE Axon 30 5G.png" },
    { name: "ZTE Red Magic 6 Pro", year: 2021, image: "/zte/ZTE Red Magic 6 Pro.png" },
    { name: "ZTE Blade V30", year: 2021, image: "/zte/ZTE Blade V30.png" },
    { name: "ZTE Axon 20 5G", year: 2020, image: "/zte/ZTE Axon 20 5G.png" },
    { name: "ZTE Blade V10", year: 2019, image: "/zte/ZTE Blade V10.png" },
    { name: "ZTE Axon 10 Pro", year: 2019, image: "/zte/ZTE Axon 10 Pro.png" },
    { name: "ZTE Blade V9", year: 2018, image: "/zte/ZTE Blade V9.png" },
    { name: "ZTE Axon 7", year: 2016, image: "/zte/ZTE Axon 7.png" },
];
